### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by lfrancke** [protomaps/basemaps-assets#2]
Thank you for providing this repository.

Could you add information about the license this and the fonts are provided under?

**Comment by bdon** [comment]
Thanks for catching this oversight - as we add more assets here the license will vary by asset type, but font PBFs are derivative works of SIL OFL fonts. I've added OFL.txt here: https://github.com/protomaps/basemaps-assets/pull/3

**Comment by lfrancke** [comment]
Thank you for the quick response.

I know it sounds like nitpicking but it'd be awesome if you could add a license for the rest as well. Without any license information the scripts and docs are not open source (which in this case I assume is not your intention) and can't be redistributed legally etc.

Also: Thank you for your work on PMTiles et. al. - that was a fabulous idea!

**Comment by bdon** [comment]
Sure, I added the BSD 3-Clause Iicense to the `scripts/` folder here, which only a very small bit of code: https://github.com/protomaps/basemaps-assets/tree/main/scripts

This repo is meant as a distribution point via GitHub pages for the non-code parts of the http://github.com/protomaps/basemaps so there isn't an umbrella license at the root. Other fonts added will be SIL OFL and image sprites will be a variant of Creative Commons.
