### ISSUE TITLE
Downloads missing

### ISSUE THREAD

**Issue by dabreegster** [protomaps/basemaps-assets#7]
Readme and GH pages say `Use the Downloads button on this repository page.`, but there dont' seem to be any GH Releases on the repo that're public

**Comment by bdon** [comment]
Here: ![CleanShot 2024-08-20 at 09 01 42@2x](https://github.com/user-attachments/assets/80fee982-1b65-4983-b204-8197db8d07a8)

What would be a better way to point to this?

**Comment by bdon** [comment]
Updated in https://github.com/protomaps/basemaps-assets/commit/853acf2ca75c00bb926644ce6904a6235337e921

**Comment by dabreegster** [comment]
Thanks and sorry for not replying/sending a PR. I didn't realize the assets are just checked into the git repo.
